Fix issues with global_search(): add the filter parameter (#589)
* this commit will fix issues with global_search()

I was recently getting this error on app.global_search() method:
```
  File "/home/poki/.local/lib/python3.8/site-packages/pyrogram/methods/messages/search_global.py", line 71, in search_global
    raw.functions.messages.SearchGlobal(
TypeError: __init__() missing 3 required keyword-only arguments: 'filter', 'min_date', and 'max_date'
```

Suprisingly no one has opened an issue for this except me.

Here is the context: https://t.me/pyrogramchat/281087

I personally use this method to fetch my global searches into my userbot with is an actual bot. little hacky >_o

* Added filter= parameter

- An Optional Parameter for global search

* Update search_global.py

Co-authored-by: Dan <14043624+delivrance@users.noreply.github.com>